services:
  blockchain:
    build: ./blockchain
    container_name: ormuz_blockchain
    ports:
      - "8545:8545"
    networks:
      - ormuz_web3_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  companhia_go:
    image: <dockerhub-usuario>/companhia_oracle:latest
    container_name: companhia_principal
    depends_on:
      blockchain:
        condition: service_healthy
    environment:
      BLOCKCHAIN_RPC: ws://blockchain:8545
      CONTRACT_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      MEU_SETOR: SETOR_PRINCIPAL
    networks:
      - ormuz_web3_net
    ports:
      - "48080:48080/udp"
      - "48081:48081/tcp"
      - "48082:48082/tcp"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  drone_1:
    image: <dockerhub-usuario>/drone_patrulha:latest
    container_name: drone_patrulha_1
    depends_on:
      - companhia_go
    environment:
      SERVER_ADDR: companhia_principal:48082
      DRONE_ID: DRONE_ALFA
    networks:
      - ormuz_web3_net
    restart: always

  drone_2:
    image: <dockerhub-usuario>/drone_patrulha:latest
    container_name: drone_patrulha_2
    depends_on:
      - companhia_go
    environment:
      SERVER_ADDR: companhia_principal:48082
      DRONE_ID: DRONE_BETA
    networks:
      - ormuz_web3_net
    restart: always

networks:
  ormuz_web3_net:
    driver: bridge