services:
  blockchain:
    build: ./blockchain
    container_name: ormuz_blockchain
    ports:
      - "8545:8545"
    networks:
      - rede_ormuz
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  servidor_go:
    build: ./servidor
    container_name: ormuz_oracle
    depends_on:
      blockchain:
        condition: service_healthy
    environment:
      MEU_SETOR: SETOR_01
      BLOCKCHAIN_RPC: ws://blockchain:8545
      CONTRACT_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3" # Endereço padrão Hardhat Local (ajustável no deploy real)
    networks:
      - rede_ormuz
    ports:
      - "48080:48080/udp"
      - "48081:48081/tcp"
      - "48082:48082/tcp"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  drone_1:
    build: ./drone
    container_name: drone_alfa
    depends_on:
      - servidor_go
    environment:
      SERVER_ADDR: servidor_go:48082
      DRONE_ID: DRONE_ALFA
    networks:
      - rede_ormuz
    restart: always

  drone_2:
    build: ./drone
    container_name: drone_beta
    depends_on:
      - servidor_go
    environment:
      SERVER_ADDR: servidor_go:48082
      DRONE_ID: DRONE_BETA
    networks:
      - rede_ormuz
    restart: always

networks:
  rede_ormuz:
    driver: bridge