services:
  servidor_a:
    build: ./servidor
    container_name: servidor_ormuz_a
    environment:
      MEU_SETOR: SETOR_A
      PEERS: servidor_b:48084,servidor_c:48084
    networks:
      - rede_ormuz
    ports:
      - "48080:48080/udp"
      - "48081:48081/tcp"
      - "48082:48082/tcp"
      - "48083:48083/tcp"
    restart: always

  servidor_b:
    build: ./servidor
    container_name: servidor_ormuz_b
    environment:
      MEU_SETOR: SETOR_B
      PEERS: servidor_a:48084,servidor_c:48084
    networks:
      - rede_ormuz
    ports:
      - "48090:48080/udp"
      - "48091:48081/tcp"
      - "48092:48082/tcp"
      - "48093:48083/tcp"
    restart: always

  servidor_c:
    build: ./servidor
    container_name: servidor_ormuz_c
    environment:
      MEU_SETOR: SETOR_C
      PEERS: servidor_a:48084,servidor_b:48084
    networks:
      - rede_ormuz
    ports:
      - "48100:48080/udp"
      - "48101:48081/tcp"
      - "48102:48082/tcp"
      - "48103:48083/tcp"
    restart: always

  dashboard:
    build: ./dashboard
    container_name: dashboard_operador
    depends_on:
      - servidor_a
      - servidor_b
      - servidor_c
    environment:
      SERVER_ADDRS: servidor_a:48083,servidor_b:48083,servidor_c:48083
    networks:
      - rede_ormuz
    stdin_open: true
    tty: true
    restart: always

  drone:
    build: ./drone
    container_name: drone_01
    depends_on:
      - servidor_a
      - servidor_b
      - servidor_c
    environment:
      SERVER_ADDRS: servidor_a:48082,servidor_b:48082,servidor_c:48082
      DRONE_ID: DRONE_01
    networks:
      - rede_ormuz
    restart: always

  radar_tcp:
    build: ./radar_tcp
    container_name: radar_tcp_01
    depends_on:
      - servidor_a
      - servidor_b
      - servidor_c
    environment:
      SERVER_ADDRS: servidor_a:48081,servidor_b:48081,servidor_c:48081
      SENSOR_ID: RADAR_01
      SENSOR_TIPO: RADAR
    networks:
      - rede_ormuz
    restart: always

  sensor_tlm:
    build: ./sensor_tlm
    container_name: sensor_tlm_01
    depends_on:
      - servidor_a
      - servidor_b
      - servidor_c
    environment:
      SERVER_ADDRS: servidor_a:48080,servidor_b:48080,servidor_c:48080
      SENSOR_ID: BOIA_01
    networks:
      - rede_ormuz
    restart: always

networks:
  rede_ormuz:
    driver: bridge
    